name: parking_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  intl: ^0.20.2
  dio: ^5.8.0+1
  provider: ^6.1.5
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_spinkit: ^5.2.1
  google_maps_flutter: ^2.12.2
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
